# Use the official Prometheus image
FROM prom/prometheus

# Copy configuration file
COPY prometheus.yml /etc/prometheus/prometheus.yml

# Expose port 9090
EXPOSE 9090

# Start Prometheus with the specified config file
CMD ["--config.file=/etc/prometheus/prometheus.yml"]
