global:
  scrape_interval: 15s  # How frequently to scrape targets

scrape_configs:
  - job_name: "fastapi-backend"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["host.docker.internal:8000"]
