
name: 'Build and Deploy to GKE'

on:
  push:
    branches: [main]


jobs:
  setup-build-publish-deploy:
    name: 'Setup, Build, Publish, and Deploy'
    runs-on: 'ubuntu-latest'
    environment: 'production'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332' # actions/checkout@v4

      # Install gcloud cli
      - name: 'Install gcloud cli' 
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          project_id: '${{secrets.GOOGLE_PROJECT_ID}}'
          service_account_key: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'
          export_default_credentials: 'true'

      # Run tests
      - name: 'Run Tests'
        run: |-
          mkdir -p configs
          touch configs/config.yaml  # Add a dummy file
          cd Frontend
          npm cache clean --force
          npm install --legacy-peer-deps --verbose
          NODE_OPTIONS="--max_old_space_size=4096" npm run build
        env:
          CI: false  # Prevents warnings from failing the build

          
      # Build the Docker image
      - name: 'Build and push Docker container'
        run: |-
          gcloud auth configure-docker us-central1-docker.pkg.dev
          docker build -t my-app:latest .
          docker push my-app:latest
